SurfSpot.create!([
  {name: "Lyall Bay", description: "Surf is great when it is on. The Airport End is where I surf the most and has a break of the wall. Other parts of the beach can be good at times.\r\nSoutherly swell, northerly wind.", place: "Wellington", region: "Wellington", country: "New Zealand", latitude: -41.328796, longitude: 174.803866, stoke_rating: 5},
  {name: " Uretiti Beach", description: "This beach is in Bream Bay. Discovered while camping at the DOC campsite. Pretty cool surf beach for beginners, kind of where I first got into it. Oh and in summer it is nice and warm!!", place: "Bream bay", region: "Northland", country: "New Zealand", latitude: -35.934883, longitude: 174.462012, stoke_rating: 4},
  {name: "Ngaranui Beach", description: "The long flat sandy bottomed beach offers nice surfing options for beginners to expert surfers. All year long, the beach  provides the perfect environment for our beginners to intermediate lessons. It is Raglans’ main swimming beach, patrolled by lifeguards with surfing allowed all down the beach on either side of the safety flags. This the best options for most surfers with limited experience.", place: "Raglan", region: "Waikato", country: "New Zealand", latitude: -37.818446, longitude: 174.82833, stoke_rating: 8},
  {name: "Tawharanui", description: "Tawharanui is a beach break on a sandy/Rocky beach, also known as Anchor Bay, located south of Omaha, on the Tawharanui Peninsula. There are several peaks along the beach to choose from with both right and left handers.", place: "Tawharanui Peninsula", region: "East Cost north of Auckland", country: "New Zealand", latitude: -36.368742, longitude: 174.835348, stoke_rating: 5},
  {name: "Piha", description: "Piha features a solid beach break which is well regarded as a top surf beach in New Zealand. South Piha often has a good left hander off Camel Rock. There are good peaks with left and right handers off both sides of Lion Rock, which can get heavy double-ups from thw back wash", place: "Piha", region: "Auckland", country: "New Zealand", latitude: -36.955523, longitude: 174.468435, stoke_rating: 4},
  {name: "Ngarunui Beach", description: "Ngarunui Beach at Raglan is a beach break on a sandy beach. There are various peaks to choose from along the beach. The wave offers both right and left handers, and can get good hollow barrels with a bit of power. Best on a higher tide. Good for beginners to expert surfers.", place: "Raglan", region: "Waikato", country: "New Zealand", latitude: -37.818491, longitude: 174.82823, stoke_rating: 8},
  {name: "Otaki Beach", description: "Otaki Beach is a beach break on a sandy beach. Otaki has several peaks along the beach to choose from with both right and left handers. The wave is small and soft, great for beginners.", place: "Otaki", region: "Horowhenua", country: "New Zealand", latitude: -40.73661, longitude: 175.115652, stoke_rating: 4},
  {name: "Westward Ho!", description: "Slow, crumbly, beginner-friendly waves. Car park by the beach and plenty of facilities.", place: "Westward Ho!", region: "North Devon", country: "England", latitude: 51.052082, longitude: -4.236023, stoke_rating: 4}
])
